services:
  stream-server:
    build: .
    container_name: kick-stream-server
    ports:
      - "1935:1935"
    volumes:
      - ./assets:/assets
      - ./nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    environment:
      - KICK_STREAM_URL
      - KICK_STREAM_KEY
      - FALLBACK_VIDEO
    restart: unless-stopped
