rtmp {
server{
listen 1935;
chunk_size 4096;
 
#Enable live broadcast service
application live {
    live on;
    record off;
    
    #Push, restream RTMP
    # push rtmp://live.twitch.tv/app/$KICK_STREAM_KEY;
    # push rtmp://a.rtmp.youtube.com/live2/$KICK_STREAM_KEY;
    push rtmp://fa723fc1b171.global-contribute.live-video.net/app/$KICK_STREAM_KEY;
}}}